//---------------------------------------
//        Macro file for test30
//         examine PostStepDoIt 
//        for hadronic physics INCL/ABLA fission
//      by aatos.heikkien@cern.ch
//--------------------------------------- 
#verbose
0
#events
1000
//--------Proton_processes
#particle
proton
//--------
#material
U
#energy(MeV)
120.
#sigmae(MeV)
0.0
#emax(MeV)
120.
#nbinse
70
#nbinsd
70
#elim(MeV)
2.
#nangle
5
#angles
7.5 30. 60. 120. 150.
#dangle
10.
//--------
#generator
incl
#paw
inclUProton1200.root
#run
#generator
bertini
#paw
bertiniUProton1200.root
#run
//--------Exit
#exit
